name: Auto Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - "go.mod"
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Extract Caddy Version
        id: caddy_version
        run: |
          VERSION=$(grep 'github.com/caddyserver/caddy/v2' go.mod | awk '{print $2}')
          echo "Full Version: $VERSION"

          # Clean version
          CLEAN_VERSION=$(echo $VERSION | sed 's/+.*//')

          echo "detected_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          echo "Detected Caddy Version: $CLEAN_VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.caddy_version.outputs.detected_version }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.caddy_version.outputs.detected_version }} already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${{ steps.caddy_version.outputs.detected_version }} does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.caddy_version.outputs.detected_version }}" -m "Release ${{ steps.caddy_version.outputs.detected_version }}"
          git push origin "${{ steps.caddy_version.outputs.detected_version }}"
